### ISSUE TITLE
DP : Discrete production (SDD)

### ISSUE THREAD

**Issue by ramakrishnan7** [astpl1998/Freudenberg#2]
@Harishkanna6 

Kindly prepare SDD for Discrete Production and attach the same. Also upload the videos for production which you have recorded during the session at FPMI,

Thanks & Regards
N Ramakrishnan

**Comment by Duraisingam-G** [comment]
Production Revised SDD Ver-1.1 for our ref. 

[FPMIPL_Discrete_Production SDD_V 1.1.docx](https://github.com/astpl1998/Freudenberg/files/6405399/FPMIPL_Discrete_Production.SDD_V.1.1.docx)

**Comment by Harishkanna6** [comment]
Production Revised SDD Ver 1.1-Final for our ref.

[FPMIPL_Discrete_Production SDD_V 1.1 -Final.docx](https://github.com/astpl1998/Freudenberg/files/6577006/FPMIPL_Discrete_Production.SDD_V.1.1.-Final.docx)

**Comment by ramakrishnan7** [comment]
Freudenberg SDD has been reviewed and submitted on 19 May 2021
