### ISSUE TITLE
IMP-Discrete Production Process study discussion

### ISSUE THREAD

**Issue by ramakrishnan7** [astpl1998/Freudenberg#8]
IMP-Discrete Production Process study discussion

**Comment by Harishkanna6** [comment]
Please find the MOM and BMR for our ref.

[MOM -Production-29th March 21.docx](https://github.com/astpl1998/Freudenberg/files/6577031/MOM.-Production-29th.March.21.docx)
[MOM -Production-30th March 21.docx](https://github.com/astpl1998/Freudenberg/files/6577033/MOM.-Production-30th.March.21.docx)
[BMR New - Discrete Production.xlsx](https://github.com/astpl1998/Freudenberg/files/6577037/BMR.New.-.Discrete.Production.xlsx)

**Comment by ramakrishnan7** [comment]
MOM and BMR study completed on 30 March 2021

**Comment by ramakrishnan7** [comment]
MOM and BMR submitted on 8th Apr 2021
